### PR TITLE
Fix pan using half-difference

### LINKED ISSUE #68: Fix Pan
It's a bit messed up. I'll fix it later.

### PR DESCRIPTION
**Pull request by Davejkane**
The solutions was obvious the whole time. This closes [#68](https://github.com/Davejkane/riv/issues/68)

### CODE REVIEW

**Review by gurgalex — CHANGES_REQUESTED** [review]
@Davejkane 

Zooming out (< 100%) does not keep the image centered anymore.
Pressing `Z` will recenter.

**Comment by Davejkane** [comment]
@gurgalex the zoom out is the same as it was originally before I broke it. I prefer this way. If you now zoom in to a pin prick and zoom all the way out until you can barely see the picture, zooming in again will land you on the same pin prick, and I like that.

You might have a point though. Are you suggesting that when the image is smaller than the screen that it shouldn't be possible to pan?

**Comment by gurgalex** [comment]
I'm saying that zooming out when at an offset results in an off center zoom out (see screenshot)

1. Zoom in on an image past 100%
2. Offset all the way to the left
3. Zoom out to say 50%

Screenshot from 2019-05-29 00-23-35

**Comment by gurgalex** [comment]
Yeah, I like the pin-prick zoom mechanic.

I expected zooming in, offsetting, and then zooming out to 50% to have an image like this.

Screenshot from 2019-05-29 00-27-48

**Comment by gurgalex** [comment]
Hmm, I don't mind the layout after playing with it for a bit.

Let's go with this for now.

**Comment by gurgalex** [comment]
Though, it still looks weird when zoomed out (I think I'm expecting it to zoom in on the place we were zoomed in on)

**Review by gurgalex — APPROVED** [review]

**Comment by Davejkane** [comment]
I mean, it would be possible to make the image centered when zoomed out till the picture is small than screen, while still preserving the offset when you zoom back in. But I had it working like that at one point and it seemed unintuitive.

**Comment by gurgalex** [comment]
Yeah, this view of zooming in and out makes more sense.

**Pull request merged**
