### PR TITLE
Implement Flip Horizontal and Vertical

### LINKED ISSUE #88: Flip image. Vertical and Horizontal
# Goal

Be able to flip an image either horizontally or vertically.

# Implementation

* Add two new keys, `H` and `V` might be good choices.
* SDL2 will definitely have a way to flip and image
* Vertical and horizontal flips could probably be booleans in the ui state.

### PR DESCRIPTION
**Pull request by gurgalex**
This PR closes #88 

Only issue I've seen is that flipping while zoomed in requires a bunch of GPU memory.
SDL2 fails to render the image saying that it is `Out of Memory`.

### CODE REVIEW

**Review by Davejkane — COMMENTED** [review]
That's really weird with how slow it goes on zoomed flipped images. Is there anything that can be done about that?

**Comment by gurgalex** [comment]
I encountered the slowness in Dev builds, but very little in release mode.

**Comment by Davejkane** [comment]
I always build release mode, and when I flipped an image and then zoomed in, the zooming is way noticeably slower, and almost grinds to a halt while still not crazy zoomed.

**Comment by gurgalex** [comment]
You're right.

**Comment by Davejkane** [comment]
That really fixed it.

**Review by Davejkane — APPROVED** [review]
LGTM. Please squash and merge.

**Comment by gurgalex** [comment]
Switching to hardware acceleration seemed to resolve the slow images.

However, images larger than 16384 in either dimension will no longer be supported by the program. We'd need to render the images in multiple parts.

```
Failed to render image Texture dimensions are limited to 16384x16384
```

**Comment by gurgalex** [comment]
@Davejkane 
I think my issue should be handled in a separate PR.

**Comment by Davejkane** [comment]
Haha, where did you even find a picture that big! What do you want the separate PR to be, handling huge images, or handling slow zoom on flipped pictures?

**Comment by gurgalex** [comment]
@Davejkane 
The separate issue should be handling images larger than the GPU can render in one go.
[info here](https://forums.libsdl.org/viewtopic.php?p=49643)

I took a snapshot with dev tools of a really long blog post.
[screencapture-hoverbear-org-2016-10-12-rust-state-machine-pattern-2019-05-25-19_57_08](https://user-images.githubusercontent.com/28968644/58767283-8366b380-854e-11e9-87da-3c33aec4ec3d.png)

**Pull request merged**
