### PR TITLE
Add Trash Support for all supported platforms

### PR DESCRIPTION
**Pull request by gurgalex**
One piece at a time.

In pursuit of #66 

- [x] Linux

* Accomplished through development of https://github.com/gurgalex/trash
Added version `0.1.0` as a git dependency to the project.

Currently only correctly moves files/directories and updates the trash info in `$XDG_DATA_HOME/Trash` directory. Supports non-utf8 file paths.

It does not implement anything else from the spec.
https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html

- [x] MacOS

* Uses `trash` [program](https://formulae.brew.sh/formula/trash) from brew to move files to the trash.

- [x] Windows 10
* Had to use the [depreciated ShFileOperationW API](https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shfileoperationw) since winapi `0.3.7` does not implement the new `IFileOperation` API since Windows Vista.

### CODE REVIEW

**Comment by gurgalex** [comment]
@Davejkane 

All that's left is MacOS trash support, which seems like it may be the most difficult to get bindings working for. Could default to just moving files to a user specified folder as a stopgap.

**Comment by gurgalex** [comment]
@Davejkane 

I've got OS specifc trash support implemented for Linux, Windows, and Mac OS.

Do we still need the cli arg for specifying a trash folder?

**Comment by Davejkane** [comment]
@gurgalex Sorry I've been on vacation. Still am actually. But having a look at this now.

**Review by Davejkane — CHANGES_REQUESTED** [review]
Man, amazing work. So many thanks for this. On mac, if I try to trash an image without having trash installed, I cause the program to panic. Can we make the absence of the program cause an error and print it to screen instead? Alternatively, we could check for trash program initialisation and exit with an error message telling them to install it perhaps? 

That's my only problem, once that's resolved I think we're good to go. Thanks once again.

**Comment by gurgalex** [comment]
@Davejkane
I went with an error message while trying to trash a file.

With this method, no crash will occur if the `trash` binary is moved or deleted while `riv` is running.
Plus, `riv` doesn't need to be restarted to get trash support working again.

**Review by Davejkane — APPROVED** [review]
Awesome. Just gave it a try after uninstalling Trash. Thumbs up from me. Please squash and merge.

**Pull request merged**
